/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import changea.Control;
import interfaces.ChangeAInterface;

/**
 *
 * @author TOcvfan
 */
public class GameOver extends javax.swing.JFrame {
    
    private ChangeAInterface control = new Control();

    /**
     * Creates new form GameOver
     */
    public GameOver() {
	initComponents();
	this.setLocationRelativeTo(null);
	this.setSize(600, 425);
	control.load();
	
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonHighScores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonExit.setText("Exit and save");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(250, 230, 120, 23);

        jButtonHighScores.setText("High Scores");
        jButtonHighScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHighScoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHighScores);
        jButtonHighScores.setBounds(250, 270, 120, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Game Over");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 280, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/images/verden.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        control.save();
	System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonHighScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHighScoresActionPerformed
        control.save();
	GUIHighScores h = new GUIHighScores();
	h.setVisible(true);
	this.setVisible(false);
    }//GEN-LAST:event_jButtonHighScoresActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHighScores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
