/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import changea.Control;
import changea.Drugs;
import interfaces.ChangeAInterface;
import java.awt.List;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;

/**
 *
 * @author Christian
 */
public class GUIBuySell extends javax.swing.JFrame {

    private ChangeAInterface control;
    DefaultListModel drugList = new DefaultListModel();
    DefaultListModel inList = new DefaultListModel();

    /**
     * Creates new form GUIBuy
     */
    public GUIBuySell(ChangeAInterface control) {
	initComponents();
	this.control = control;
	setLocationRelativeTo(null);
	this.setSize(610, 435);
	jListInven.setModel(inList);
	jListDrugs.setModel(drugList);
	addToList();
	addInventory();
//	jLabelDrugs.setText(control.userDrugsMoney());
	jLabelMoney.setText(control.userStock(1));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSell = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonBuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelDrugs = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDrugs = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInven = new javax.swing.JList();
        jTextFieldSell = new javax.swing.JTextField();
        jTextFieldBuy = new javax.swing.JTextField();
        jLabelbaggrund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSell.setText("Sell");
        jButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSell);
        jButtonSell.setBounds(360, 310, 60, 30);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(523, 363, 70, 30);

        jButtonBuy.setText("Buy");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuy);
        jButtonBuy.setBounds(30, 310, 60, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAFIA GAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 40);

        jLabelDrugs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDrugs.setText("Drugs you have");
        jLabelDrugs.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelDrugs);
        jLabelDrugs.setBounds(360, 50, 180, 190);

        jLabelMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMoney.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMoney.setText("Money");
        getContentPane().add(jLabelMoney);
        jLabelMoney.setBounds(240, 350, 140, 30);

        jListDrugs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListDrugs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jListDrugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDrugsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListDrugs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 240, 190);

        jListInven.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListInven.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jListInven);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 70, 210, 190);
        getContentPane().add(jTextFieldSell);
        jTextFieldSell.setBounds(360, 270, 60, 30);
        getContentPane().add(jTextFieldBuy);
        jTextFieldBuy.setBounds(30, 270, 60, 30);

        jLabelbaggrund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/images/verden.PNG"))); // NOI18N
        getContentPane().add(jLabelbaggrund);
        jLabelbaggrund.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
	this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jListDrugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDrugsMouseClicked

    }//GEN-LAST:event_jListDrugsMouseClicked

    private void jButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellActionPerformed
        int dSell = jListInven.getSelectedIndex();
	String userSellInput = jTextFieldSell.getText();
	int sellAmount = 1;

	if (!userSellInput.equals("")) {
	    sellAmount = Integer.parseInt(userSellInput);
	}
	if (dSell >= 0) {

	    control.sell(dSell, sellAmount);

	    drugList.clear();
	    inList.clear();
	    addToList();
	    addInventory();
	    jLabelMoney.setText(control.userStock(1));
	}
	jTextFieldSell.setText("");
    }//GEN-LAST:event_jButtonSellActionPerformed

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        int dBuy = jListDrugs.getSelectedIndex();
	String userBuyInput = jTextFieldBuy.getText();
	int buyAmount = 1;

	if (!userBuyInput.equals("")) {
	    buyAmount = Integer.parseInt(userBuyInput);
	}
	if (dBuy >= 0) {
	    control.buy(dBuy, buyAmount);
	    drugList.clear();
	    inList.clear();
	    addToList();
	    addInventory();
	    jLabelMoney.setText(control.userStock(1));
	}
	jTextFieldBuy.setText("");
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void addToList() {
	Drugs[] drugs = control.getNewDrugStats();
	for (int i = 0; i < 10; i++) {
	    drugList.addElement(drugs[i].getDrugName() + ": " + drugs[i].getAvailBase() + " Bags Price: " + drugs[i].getDrugBasePrice() + "$");

	}

    }

    private void addInventory() {
	Drugs[] inven = control.getInventory();
	for (int i = 0; i < 10; i++) {
	    inList.addElement(inven[i].getDrugName() + ": " + inven[i].getAvailBase() + " Bags");

	}

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDrugs;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelbaggrund;
    private javax.swing.JList jListDrugs;
    private javax.swing.JList jListInven;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBuy;
    private javax.swing.JTextField jTextFieldSell;
    // End of variables declaration//GEN-END:variables

}
