/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import changea.Control;
import entity.User;
import interfaces.ChangeAInterface;
import java.util.ArrayList;

/**
 *
 * @author Christian
 */
public class GUIHighScores extends javax.swing.JFrame {
    
    private ChangeAInterface control = new Control();
    ArrayList<User> list;
    private int cocaine, heroin;

    /**
     * Creates new form GUISell
     */
    public GUIHighScores() {
	initComponents();
	setLocationRelativeTo(null);
	this.setSize(600, 425);
	control.load();
	
	//jLabelList.setText("High scores");
	jTextAreaScores.setText(control.getHighScore());
    }

    /*
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Drug = new javax.swing.JLabel();
        jLabeltitel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonStartMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelbaggrund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1Drug.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1Drug.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1Drug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Drug.setText("High Scores");
        getContentPane().add(jLabel1Drug);
        jLabel1Drug.setBounds(0, 50, 600, 30);

        jLabeltitel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeltitel.setForeground(new java.awt.Color(153, 0, 153));
        jLabeltitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitel.setText("MAFIA GAME");
        getContentPane().add(jLabeltitel);
        jLabeltitel.setBounds(0, 0, 600, 40);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(495, 353, 90, 30);

        jButtonStartMenu.setText("Start Menu");
        jButtonStartMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStartMenu);
        jButtonStartMenu.setBounds(10, 343, 120, 40);

        jTextAreaScores.setEditable(false);
        jTextAreaScores.setColumns(20);
        jTextAreaScores.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaScores.setForeground(new java.awt.Color(0, 0, 255));
        jTextAreaScores.setRows(10);
        jScrollPane1.setViewportView(jTextAreaScores);
        jTextAreaScores.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(206, 80, 180, 280);

        jLabelbaggrund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/images/verden.PNG"))); // NOI18N
        getContentPane().add(jLabelbaggrund);
        jLabelbaggrund.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonStartMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartMenuActionPerformed
        GUIStart s = new GUIStart();
	s.setVisible(true);
	this.setVisible(false);
    }//GEN-LAST:event_jButtonStartMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonStartMenu;
    private javax.swing.JLabel jLabel1Drug;
    private javax.swing.JLabel jLabelbaggrund;
    private javax.swing.JLabel jLabeltitel;
    private javax.swing.JScrollPane jScrollPane1;
    private final transient javax.swing.JTextArea jTextAreaScores = new javax.swing.JTextArea();
    // End of variables declaration//GEN-END:variables
}
